### ISSUE TITLE
overture.bio colour audit for accessibility

### ISSUE THREAD

**Issue by kcullion** [overture-stack/roadmap#118]
Please make the following updates for accessibility:

**Global styles**:
- [x] Content links: underline and make #0B75A2
- [x] Colourful product category badges - mega menu, homepage(https://zpl.io/2ppoKLM), documentation landing page (https://zpl.io/bPw4ovM), and individual product pages.
- [x] Large teal buttons: make dark blue #04518C 
- [x] Except when they show up on the dark blue background...then make them magenta:see bottom of Song page:  https://zpl.io/2ppoQvQ
- [x] Footer: change light teal headings to blue: #04518C. The Privacy and Terms links adopt the general link style

**Product landing page**:
- [x] Make all background sections white (even core products), make the "CORE" tag a darker blue, and change the product category titles to new darker colours: https://zpl.io/bAeG0Mp

**Docs pages**
- [x] The "Documentation Overview" back link - use same global link colour #0B75A2, but no underline. Github buttons are the dark blue too: https://zpl.io/VDXGQzr 
- [x] for code highlight in the dark blue callout box, make dark blue instead of light blue (#003055)
![image](https://user-images.githubusercontent.com/18424138/101795067-82182e80-3ad5-11eb-962b-feb8799c1a1c.png)

nice to have:

- [ ] Add alt text to non decorative images like the screenshots on these pages: 
https://www.overture.bio/products/ego
https://www.overture.bio/products/arranger/
https://www.overture.bio/products/oncojs/
logos and screenshots (if possible) https://www.overture.bio/case-studies/

**Comment by samrichca** [comment]
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/288ddda8-5e7f-44c0-8451-ef89ac58e330)

made the DMS bundle/dark blue badges white-on-blue

I'd like to do the alt tags as their own ticket though

**Comment by samrichca** [comment]
updating the site with these colours:

https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5f47cb6ac82346330dcc9a4e

**Comment by samrichca** [comment]
https://github.com/overture-stack/website/pull/103

**Comment by samrichca** [comment]
https://6005c79371e7df8184c98740--overture.netlify.app
