### ISSUE TITLE
Upgrade DMS to Arranger 3.0

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#150]
Upgrade DMS to Arranger 3.0, which includes the following tasks:

## DMS: ##

- [ ] Investigate fix DMS' ability to run locally on supported OS/environments
- [ ] Update DMS dependencies to latest versions, with priority on components that enable J-Browse integration:
    - [ ] Arranger
    - [ ] DMS UI
    - [ ] ElasticSearch
 - [ ] Update DMS script to account for the new Arranger 3.0 configs
 - [ ] Documentation updates for the above version and config changes
 
**NOTE:** The work above unblocks the following ticket: https://github.com/overture-stack/dms/issues/163

## DMS-UI: ##

- [ ] Verify the ported Arranger 3.0 upgrades that were put into the DMS-UI J-Browse integration
