### ISSUE TITLE
Finish Ego Integration for Song/Score

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/roadmap#8]
- [x] Data Model for API Keys/Tokens
- [x] Draw the diagram to grab JWT/interpert first
- [x] Remove DACO/ICGC Auth dependency in SONG

The expectation is that the SONG should require EGO authorization method 
This should not affect the current ICGC SONG implementation

This is an epic for the activity. To be edited

**Comment by andricDu** [comment]
https://github.com/overture-stack/ego/issues/152
